"""add frequency to habits

Revision ID: 58d8cf90abee
Revises: 528d1c3abfde
Create Date: 2026-03-11 02:36:36.301569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d8cf90abee'
down_revision: Union[str, None] = '528d1c3abfde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('frequency', sa.String(), nullable=True))
    op.add_column('habits', sa.Column('times_per_period', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habits', 'times_per_period')
    op.drop_column('habits', 'frequency')
    # ### end Alembic commands ###
